# Generated by Arara Revenue OS - Dockerizing the Future of Payments

# --- Stage 1: Build ---
FROM node:20-slim AS builder

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source and config
COPY tsconfig.json ./
COPY src ./src

# Build TypeScript
RUN npm run build

# --- Stage 2: Runtime ---
FROM node:20-slim AS runtime

WORKDIR /app

# Set production environment
ENV NODE_ENV=production

# Copy only necessary files from builder
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/build ./build

# Install production dependencies only
RUN npm install --omit=dev

# Standard MCP port (dedicated for Arara MCP)
EXPOSE 8080

# Default command (stdio)
# To run as SSE, you can override this with: --transport sse (once implemented)
ENTRYPOINT ["node", "build/index.js"]
