import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerAuthTools } from "./auth.js";
import { registerMessagingTools } from "./messaging.js";
import { registerTemplateTools } from "./templates.js";
import { registerCampaignTools } from "./campaigns.js";
import { registerContactTools } from "./contacts.js";
import { registerConversationTools } from "./conversations.js";
import { registerBrainTools } from "./brain.js";
import { registerSmartLinkTools } from "./smart_links.js";
import { registerRecoveryTools } from "./recovery.js";
import { registerNumberTools } from "./numbers.js";
import { registerAccountTools } from "./account.js";
import { registerApiKeyTools } from "./api_keys.js";
import { registerPhoneLookupTools } from "./phone_lookup.js";
import { registerGuardianTools } from "./guardian.js";
import { registerAbacateTools } from "./abacate.js";
import { registerOptOutTools } from "./opt_outs.js";
import { registerPricingTools } from "./pricing.js";
import { registerAbTestTools } from "./ab_test.js";
import { registerPolicyTools } from "./policy.js";
import { registerBusinessProfileTools } from "./business_profile.js";
import { registerLgpdTools } from "./lgpd.js";
import { registerWarmingTools } from "./warming.js";

export const registerAllTools = (server: McpServer): void => {
  registerAuthTools(server);
  registerMessagingTools(server);
  registerTemplateTools(server);
  registerCampaignTools(server);
  registerContactTools(server);
  registerConversationTools(server);
  registerBrainTools(server);
  registerSmartLinkTools(server);
  registerRecoveryTools(server);
  registerNumberTools(server);
  registerAccountTools(server);
  registerApiKeyTools(server);
  registerPhoneLookupTools(server);
  registerGuardianTools(server);
  registerAbacateTools(server);
  registerOptOutTools(server);
  registerPricingTools(server);
  registerAbTestTools(server);
  registerPolicyTools(server);
  registerBusinessProfileTools(server);
  registerLgpdTools(server);
  registerWarmingTools(server);
};
